### ISSUE TITLE
Missing a t12 possible loadout

### ISSUE THREAD

**Issue by SableCentaur** [GeekyEggo/DestinyTailor#8] opened 2016-07-10 19:58 UTC
This is the first time I've had this problem with the tool, but I think it has to do with the class item in this case. When I look at the loadout builder, it does not have an option for a 5-4-3 setup, but as you can see in the second image, it is very possible for me to get that loadout. Note that my cloak appears to have no stat rolls on it, but it actually has a roll of 47 intellect with a node bonus of 10 that can go to either discipline or strength, which I think is the source of this issue.
![ex1](https://cloud.githubusercontent.com/assets/20386522/16715745/3d692dfc-46a6-11e6-8970-b17037e86c61.png)
![ex2](https://cloud.githubusercontent.com/assets/20386522/16715744/3d66e736-46a6-11e6-965f-9fa7a78ef2d7.png)

**Comment by GeekyEggo** [comment] 2016-07-11 13:06
Thanks for reporting this @SableCentaur. I think you're right, and I think it's being caused by exotic class items being an edge case by being the only item that includes combinations for all 3 stats, e.g. int / disc, or int / str.

An example of this is with my Titan ([destinytailor.com/psn/geekyeggo/titan](http://destinytailor.com/psn/geekyeggo/titan), who is currently wearing the "Mark of the Sunforged". I'll look into fixing this as soon as possible.

**Comment by GeekyEggo** [comment] 2016-07-13 13:11
@SableCentaur, what's your PSN or gamer tag?

**Comment by SableCentaur** [comment] 2016-07-13 18:33
@GeekyEggo my GT is Sabie (it will show up as SabIe, but it is a capital i, not an L)

**Comment by GeekyEggo** [comment] 2016-07-15 14:14
This will hopefully be fixed in the next release; _how_ item stats are loaded has been greatly simplified, hopefully improving both accuracy and load times. Few minor amends to make, but hoping to release late this weekend.

**Closed** 2016-07-17 14:49 UTC
Labels: bug
